force-app/main/default/objects/Driver__c/fields/Age__c.field-meta.xml
<CustomField>
    <fullName>Age__c</fullName>
    <label>Age</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>18 - 25</fullName>
            </value>
            <value>
                <fullName>25 - 36</fullName>
            </value>
            <value>
                <fullName>36 - 45</fullName>
            </value>
            <value>
                <fullName>Above 45</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Driver__c/fields/Discont__c.field-meta.xml
<CustomField>
    <fullName>Discont__c</fullName>
    <label>Discont</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/DriverObjectClass.cls
public class DriverObjectClass {
        public static void driverMethod(List<Driver__c> DriverNew){
    
     for(Driver__c d : DriverNew)
        {
            if(d.Age__c != NULL) {
                
                if(d.Age__c == '18 - 25') {
                d.Discont__c= 0;
            }
             else if(d.Age__c == '25 - 36') {
                d.Discont__c= 10;
            }
            else if(d.Age__c == '36 - 45') {
                d.Discont__c= 20;
               
            }
           else if(d.Age__c == 'above 45') {
                d.Discont__c= 30;
            }
        }
        
    
}
}
}